WebhookExpirationTime. DMPD-1735
aggregion/helm-charts-cdp pull request #4
Opened 2021-10-14 13:41 UTC by AlexeyMM

2021-10-14 14:16 UTC, AlekNS requested changes

2021-10-14 14:16 UTC, AlekNS commented on charts/aggregion-cdp/templates/configmaps-backend-cfg-files.yaml
> +            "webhookUrl": "{{ .Values.backend.configs.datalabWebhookUrl }}",
запятая в конце лишняя

2021-10-14 14:16 UTC, AlekNS commented on charts/aggregion-cdp/templates/configmaps-backend-envs.yaml
> +  WEBHOOK_TOKEN_EXPIRATION_TIME: "{{ .Values.backend.configs.webhookTokenExpirationTime }}"
а зачем в конфиг и в env прописывать одно и тоже?

2021-10-14 14:17 UTC, AlekNS commented on charts/aggregion-cdp/templates/configmaps-backend-envs.yaml
> +  WEBHOOK_TOKEN_EXPIRATION_TIME: "{{ .Values.backend.configs.webhookTokenExpirationTime }}"
и да, версию поднять нужно

2021-10-15 09:29 UTC, AlekNS approved these changes

2021-10-15 09:33 UTC, serega-k approved these changes

2021-10-15 09:33 UTC, serega-k approved these changes

2021-10-15 11:05 UTC, merged